-- WARNING: test only
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE audit_logs;
TRUNCATE TABLE maintenance_logs;
TRUNCATE TABLE rentals;
TRUNCATE TABLE vehicles;
TRUNCATE TABLE users;
SET FOREIGN_KEY_CHECKS=1;
